language: node_js

env: MONGO_URI_TEST=mongodb://localhost:27017/MYBRAND_TEST

sudo: false

node_js:
  - "stable"

services:
  - mongodb

directories:
  - "node_modules"

script:
  - cd backend
  - npm install
  - npm run coveralls

notifications:
  email: false
