language: node_js

env: MONGO_URI_TEST=mongodb://localhost/MYBRAND_TEST

sudo: false

node_js:
  - "stable"

services:
  - mongodb

directories:
  - "node_modules"

script:
  - cd backend
  - npm install
  - npm run coverage

notifications:
  email: false
after_success: npm run coveralls
