language: node_js

env: MONGO_URL_TEST=mongodb://localhost:27017/blogdb

sudo: false

node_js:
  - "node"

services:
  - mongodb

directories:
  - "node_modules"

install:
  

script:
  - cd server
  - npm install
  - npm run test

after_success: 
  - npm run coverage

notifications:
  email: false