# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches:    
      - develop
  push:
    branches:    
      - develop

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: test
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Install dependencies
      working-directory: ./server
      run: npm install
    - name: Test the project
      working-directory: ./server
      run: npm run test
    - name: Coverage
      working-directory: ./server
      run: npm run coveralls
